lsi: false
safe: true

source: .

title: "Transit Store - California Integrated Mobility"
description: Lorem Ipsum Dolor Sit Amet

baseurl: ""
url: https://cal-itp-transit-store.netlify.app

collections_dir: content
collections:
  actions:
    output: false
  categories:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - bin
  - docker-compose.yml
  - netlify.toml
  - README.md
  - submodules
