baseurl: "" # the subpath of your site, e.g. /blog
domain: www.camobilitymarketplace.org
collections:
  pages:
    output: true
    permalink: /:title
description: >-
  A resource to help transit providers upgrade their fare collection systems to accept contactless payment methods like credit/debit cards and smartphones.
announcement:
  enabled: true
  text: |
    Cal-ITP is offering smaller providers in California a limited number of free
    licenses to Remixâ€™s suite of scheduling products. Check your eligibility and
    sign up using our [intake form](https://share.hsforms.com/13WkzY7taSoSdxBATWsNedQ3aanu){:target="_black"}.
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _data/
fonts: "family=Poppins:wght@400;500;700&family=Raleway:wght@700"
google_analytics_id: "G-6M5TSH3VCY"
mailing_list: https://lp.constantcontactpages.com/su/eLbtFoE/calitp?source_id=a41b99cd-7f28-4be8-a286-f9e75fc7bbce&source_type=em&c=
navigation:
  header:
    - name: Contracts
      url: /contracts/
    - name: For vendors
      url: /for-vendors
    - name: About
      url: /about
    - name: Contact us
      url: /contact
  products:
    - name: Contactless Payments
      url: /go-contactless
    - name: Data Plans
      url: /how-to/get-connected
  footer:
    - name: Back to top
      url: "#main-content"
    - name: Glossary
      url: /glossary-of-key-terms
    - name: Provider map
      url: /provider-map
    - name: Privacy policy
      url: https://dot.ca.gov/privacy-policy
      target: _blank
    - name: Conditions of use
      url: https://dot.ca.gov/conditions-of-use
      target: _blank
    - name: Register to vote
      url: https://registertovote.ca.gov/
      target: _blank
source: ./src
title: California Mobility Marketplace
theme_color: "#ffffff"
theme_color_background: "#ffffff"
url: "https://www.camobilitymarketplace.org" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
