lsi: false
safe: true

source: .

title: Transit Stop - California Integrated Travel Project
description: A one-stop resource for modern, equitable and accessible public transit products and services.

baseurl: ""
url: https://cal-itp-transit-stop.netlify.app

timezone: America/Los_Angeles

analytics:
  production: UA-176840950-1

collections_dir: content
collections:
  actions:
    output: false
  categories:
    output: true
    permalink: /:title
  posts:
    output: true
    permalink: /articles/:year/:month/:title

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - admin/plugins
  - bin
  - docker-compose.yml
  - netlify.toml
  - README.md
  - submodules
