baseurl: "" # the subpath of your site, e.g. /blog
domain: www.camobilitymarketplace.org
collections:
  pages:
    output: true
    permalink: /:title
description: >-
  A resource for transit providers on how to modernize operations and improve rider experiences through contactless fare collection, fleet connectivity, and real-time data.
defaults:
  - scope:
      path: ""
    values:
      image: /uploads/og-image.png
cta_banner:
  text: Optional banner. <b>With CTA.</b>
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _data/
include:
  - _redirects
google_analytics_id: "G-6M5TSH3VCY"
navigation:
  - name: Data plans
    url: /data-plans
  - name: Route scheduling
    url: /route-scheduling
  - name: GTFS Realtime
    url: /gtfs-realtime
  - name: Tap to pay
    url: /tap-to-pay
source: ./src
title: California Mobility Marketplace
theme_color: "#ffffff"
theme_color_background: "#ffffff"
url: "https://www.camobilitymarketplace.org" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
