baseurl: "" # the subpath of your site, e.g. /blog
domain: www.camobilitymarketplace.org
collections:
  pages:
    output: true
    permalink: /:title
description: >-
  A resource to help transit providers upgrade their fare collection systems to accept contactless payment methods like credit/debit cards and smartphones.
announcement:
  enabled: true
  text: |
    Now available! Pre-approved [MSAs for GTFS Realtime](contracts/view?contracts-filter-product=GTFS Realtime){:target="_black"} software and/or hardware. [Get started with our GTFS Realtime guide](/how-to/gtfs-rt){:target="_black"}.
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - _data/
include:
  - _redirects
fonts: "family=Poppins:wght@400;500;700&family=Raleway:wght@700"
google_analytics_id: "G-6M5TSH3VCY"
mailing_list: https://lp.constantcontactpages.com/su/eLbtFoE/calitp?source_id=a41b99cd-7f28-4be8-a286-f9e75fc7bbce&source_type=em&c=
navigation:
  - name: Data plans
    url: /
  - name: Route schedule
    url: /
  - name: GTFS Realtime
    url: /
  - name: Tap to pay
    url: /
source: ./src
title: California Mobility Marketplace
theme_color: "#ffffff"
theme_color_background: "#ffffff"
url: "https://www.camobilitymarketplace.org" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
