[build]
    command = "npm run build"

[[redirects]]
  from = "/assets/Cal-ITP.MobilityMarketplace.DataPlans.NASPO.FirstNet.pdf"
  to = "/how-to/get-connected"
  status = 301
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/contactless-support"
  to = "/contact"
  status = 301
  force = true # COMMENT: ensure that we always redirect
