[build]
    # see https://github.com/cal-itp/mobility-marketplace/pull/765 for more info about why we are calling 'bundle install' explicitly
    command = "bundle install && bundle exec jekyll build"
    environment = { JEKYLL_ENV = "development" }

[context.production]
    environment = { JEKYLL_ENV = "production" }

[[redirects]]
  from = "/assets/Cal-ITP.MobilityMarketplace.DataPlans.NASPO.FirstNet.pdf"
  to = "/how-to/get-connected"
  status = 301
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/contactless-support"
  to = "/contact"
  status = 301
  force = true # COMMENT: ensure that we always redirect
