services:
  site:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    ports:
      - "4000"
      - "35729:35729"
    volumes:
      - ..:/usr/src/mobimart
