backend:
  name: git-gateway
  branch: master
  squash_merges: true

display_url: https://cal-itp-transit-stop.netlify.app

logo_url: https://cal-itp-transit-stop.netlify.app/assets/images/logo-sm.svg

media_folder: "assets/uploads"

publish_mode: editorial_workflow

site_url: https://cal-itp-transit-stop.netlify.app

collections:
  - name: "navigation"
    label: "Navigation"
    description: "The menus on the site."
    editor:
      preview: false
    files:
      - label: "Main navigation"
        name: "nav_main"
        file: "_data/nav_main.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {
                  label: "Open in",
                  name: "target",
                  widget: "select",
                  default: { label: "Same tab", value: "_self" },
                  options: [
                    { label: "Same tab", value: "_self" },
                    { label: "New tab", value: "_blank" }
                  ]
                }

      - label: "Footer navigation"
        name: "nav_footer"
        file: "_data/nav_footer.yml"
        fields:
          - label: "Navigation items"
            label_singular: "Navigation item"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {
                  label: "Open in",
                  name: "target",
                  widget: "select",
                  default: { label: "Same tab", value: "_self" },
                  options: [
                    { label: "Same tab", value: "_self" },
                    { label: "New tab", value: "_blank" }
                  ]
                }

  - name: "pages"
    label: "Pages"
    description: "Landing pages with unique layouts and options."
    editor:
      preview: false
    preview_path: "{{slug}}"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/pages/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Social image", name: "image", widget: "image", hint: "Displayed in social shares and links." }
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "For browser tabs and social shares; combined with the site title."
            }
          - {
              label: "Hero",
              name: "hero",
              widget: "object",
              fields: [
                {label: "Headline", name: "headline", widget: "string"},
                {
                  label: "Text",
                  name: "text",
                  widget: "markdown",
                  minimal: true,
                  buttons: [
                    bold,
                    italic,
                    link,
                    bulleted-list,
                    numbered-list
                  ],
                  editor_components: []
                },
                {label: "Image", name: "image", widget: "image" }
              ]
            }
          - {
              label: "Action Panels",
              label_singular: "Action",
              name: "actions",
              widget: "relation",
              collection: "actions",
              multiple: true,
              value_field: "ref_id",
              search_fields: ["title", "text", "body"],
              display_fields: ["title"]
            }

      - label: "Provider map"
        name: "provider-map"
        file: "content/pages/provider-map.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "provider-map"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Social image", name: "image", widget: "image", hint: "Displayed in social shares and links." }
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "For browser tabs and social shares; combined with the site title."
            }
          - {label: "Headline", name: "headline", widget: "string"}
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }
          - {
              label: "About the Data",
              name: "about",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                heading-three,
                heading-four,
                heading-five,
                heading-six,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }
          - {
              label: "Data action",
              name: "action",
              hint: "Select a Call to Action item to generate a button in the About section.",
              widget: "relation",
              collection: "actions",
              value_field: "ref_id",
              search_fields: ["title", "text", "body"],
              display_fields: ["title"]
            }
          - {
              label: "Source",
              name: "source",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                heading-three,
                heading-four,
                heading-five,
                heading-six,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }

      - label: "Contact"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "form"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Social image", name: "image", widget: "image", hint: "Displayed in social shares and links." }
          - {
              label: "Title",
              name: "title",
              widget: "string",
              hint: "For browser tabs and social shares; combined with the site title."
            }
          - {label: "Headline", name: "headline", widget: "string"}
          - {
              label: "Body",
              name: "body",
              widget: "markdown",
              minimal: true,
              buttons: [
                bold,
                italic,
                link,
                bulleted-list,
                numbered-list
              ],
              editor_components: []
            }
          - {
              label: "Roles",
              label_singular: "role",
              name: "roles",
              widget: "list",
              summary: "{{fields.name}}",
              fields: [{
                label: "Name",
                name: "name",
                widget: "string"
              }]
            }
          - {
              label: "Areas of Interest",
              label_singular: "area",
              name: "areas",
              widget: "list",
              summary: "{{fields.name}}",
              fields: [
                {label: "Name", name: "name", widget: "string"},
                {label: "Description", name: "description", widget: "string"}
              ]
            }
          - {
              label: "Confirmation",
              name: "confirmation",
              widget: "object",
              summary: "{{fields.message}}",
              fields: [
                {
                  label: "Message",
                  name: "message",
                  widget: "markdown",
                  buttons: [
                    bold,
                    italic,
                    link,
                    heading-two,
                    heading-three,
                    heading-four,
                    heading-five,
                    heading-six,
                    bulleted-list,
                    numbered-list
                  ],
                  editor_components: [
                    "image",
                    "image-caption",
                    "pull-quote",
                    "youtube"
                  ]
                },
                {
                  label: "Button",
                  name: "action",
                  widget: "relation",
                  collection: "actions",
                  value_field: "ref_id",
                  search_fields: ["title", "text", "body"],
                  display_fields: ["title"]
                }
              ]
            }
          - {label: "Form include", name: "form", widget: "hidden"}

      - label: "Glossary"
        name: "glossary"
        file: "_data/glossary.yml"
        fields:
          - label: "Terms"
            label_singular: "Term"
            name: "items"
            widget: "list"
            summary: "{{fields.term}}"
            fields:
              - {label: "Term", name: "term", widget: "string"}
              - {label: "Definition", name: "definition", widget: "text"}
  - name: "actions"
    label: "Calls to Action"
    label_singular: "Call to Action"
    description: "Reusable pieces of content that generate buttons and other clickable elements."
    editor:
      preview: false
    folder: "content/_actions"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Action text", name: "text", widget: "string", hint: "Used for action buttons"}
      - {label: "Action URL", name: "href", widget: "string"}
      - {
          label: "Open in",
          name: "target",
          widget: "select",
          default: { label: "Same tab", value: "_self" },
          options: [
            { label: "Same tab", value: "_self" },
            { label: "New tab", value: "_blank" }
          ]
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          minimal: true,
          buttons: [
            bold,
            italic
          ],
          editor_components: []
        }
      - {label: "Image", name: "image", widget: "image", required: false, hint: "Used when this action is displayed in a panel (e.g. image + text + button)."}
      - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

  - name: "metadata"
    label: "Metadata"
    description: "Supporting content and configuration for the site."
    editor:
      preview: false
    files:
      - label: "Authors"
        name: "authors"
        file: "_data/authors.yml"
        fields:
          - label: "Authors"
            label_singular: "Author"
            name: "items"
            widget: "list"
            fields:
              - {label: "First name", name: "first_name", widget: "string"}
              - {label: "Last name", name: "last_name", widget: "string"}
              - {label: "Unique ID", name: "ref_id", widget: "shortid", hint: "Automatically generated"}

      - label: "Site Metadata"
        name: "meta"
        file: "_data/meta.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", hint: "Visible in the browser tab and in social share links."}
          - {label: "Description", name: "description", widget: "text", hint: "Visible in social share links for the site homepage and as a default for pages."}
          - {label: "Social image", name: "image", widget: "image", hint: "Default image for social share links (pages can override)."}
